// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhxpOxjW2mSDH6ECpDq0lMmikz5Y58g3E',
    appId: '1:991203841996:web:f1500fbbeb7ad802c0af69',
    messagingSenderId: '991203841996',
    projectId: 'lautkita-54a5f',
    authDomain: 'lautkita-54a5f.firebaseapp.com',
    storageBucket: 'lautkita-54a5f.appspot.com',
    measurementId: 'G-H2RWSMYLCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtOYidfCp-NWEqfBwF5bj60Pt1SBqWC_8',
    appId: '1:991203841996:android:b7233fc4f7aae3aac0af69',
    messagingSenderId: '991203841996',
    projectId: 'lautkita-54a5f',
    storageBucket: 'lautkita-54a5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO0kmTvWf8Oad_HKiO7JyU7e69VONsDvk',
    appId: '1:991203841996:ios:89c5cfa644179e5cc0af69',
    messagingSenderId: '991203841996',
    projectId: 'lautkita-54a5f',
    storageBucket: 'lautkita-54a5f.appspot.com',
    iosBundleId: 'com.example.lautkitaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO0kmTvWf8Oad_HKiO7JyU7e69VONsDvk',
    appId: '1:991203841996:ios:cf6035b6c1bbe619c0af69',
    messagingSenderId: '991203841996',
    projectId: 'lautkita-54a5f',
    storageBucket: 'lautkita-54a5f.appspot.com',
    iosBundleId: 'com.example.lautkitaMobile.RunnerTests',
  );
}
